from tkinter import *
root = Tk()
root.title("Student Mark-sheet")
root.geometry("450x550")
def transition():
   label_subs.destroy()
   label_name.destroy()
   label_class.destroy()
   label_eng.destroy()
   label_chem.destroy()
   label_cs.destroy()
   label_math.destroy()
   label_phy.destroy()
   entry_name.destroy()
   entry_class.destroy()
   entry_eng.destroy()
   entry_chem.destroy()
   entry_cs.destroy()
   entry_math.destroy()
   entry_phy.destroy()
   button.destroy()
def save(data, stu_name):
    file = open(f"DATA/{stu_name} data", "w")
    file.write(str(data))
    file.close()
def ShowResult():
   Name = entry_name.get()
   name = str(Name)
   Clas = entry_class.get()
   Class = str(Clas)
   english = entry_eng.get()
   eng = int(english)
   Physics = entry_phy.get()
   phy = int(Physics)
   Chemistry = entry_chem.get()
   chem = int(Chemistry)
   Cs = entry_cs.get()
   cs = int(Cs)
   mathematics = entry_math.get()
   maths = int(mathematics)
   total = eng + maths + chem + phy + cs
   avg = float(total/5)
   transition()
   student_name = Label(root, text=name)
   student_name.config(font=("Helvetica ", 15))
   student_name.pack()
   clas = Label(root, text=Class)
   clas.config(font=("Helvetica ", 15))
   clas.pack()
   student_marks = Label(root, text="student marks")
   student_marks.config(font=("Helvetica ", 15))
   student_marks.pack()
   eng_mark = f"english: {eng}"
   eng = Label(root, text=eng_mark)
   eng.config(font=("Helvetica ", 15))
   eng.pack()
   phy_mark = f"physics: {phy}"
   phy = Label(root, text=phy_mark)
   phy.config(font=("Helvetica ", 15))
   phy.pack()
   chem_mark = f"chemistry: {chem}"
   chem = Label(root, text=chem_mark)
   chem.config(font=("Helvetica ", 15))
   chem.pack()
   math_mark = f"maths: {maths}"
   math = Label(root, text=math_mark)
   math.config(font=("Helvetica ", 15))
   math.pack()
   cs_mark = f"cs: {cs}"
   cs = Label(root, text=cs_mark)
   cs.config(font=("Helvetica ", 15))
   cs.pack()
   average_mark = f"average mark: {avg}"
   average = Label(root, text=average_mark)
   average.config(font=("Helvetica ", 15))
   average.pack()
   totl = f"Total: {total}"
   total_mark = Label(root, text=totl)
   total_mark.config(font=("Helvetica ", 15))
   total_mark.pack()
   marks = []
   marks.append(eng_mark)
   marks.append(phy_mark)
   marks.append(chem_mark)
   marks.append(math_mark)
   marks.append(cs_mark)
   SAVE_BUTTON = Button(root, width=30, text="Save", bg="#1EE8AB", command=save(marks, name))
   SAVE_BUTTON.pack()
head = Label(root,text="Student marksheet")
head.config(font=("aharoni", 30))
head.pack()
label_name = Label(root, text="student name:")
label_name.pack()
entry_name = Entry(root, width=30)
entry_name.pack()
label_class = Label(root, text="class and section:")
label_class.pack()
entry_class = Entry(root, width=30)
entry_class.pack()
label_subs = Label(root, text="enter the subject marks")
label_subs.config(font=("Helvetica ", 15))
label_subs.pack(pady=10)
label_eng = Label(root, text="english:")
label_eng.pack()
entry_eng = Entry(root, width=30)
entry_eng.pack()
label_phy = Label(root, text="physics: ")
label_phy.pack()
entry_phy = Entry(root, width=30)
entry_phy.pack()
label_chem = Label(root, text="chemistry:")
label_chem.pack()
entry_chem = Entry(root, width=30)
entry_chem.pack()
label_math = Label(root, text="maths:")
label_math.pack()
entry_math = Entry(root, width=30)
entry_math.pack()
label_cs = Label(root, text="computer science:")
label_cs.pack()
entry_cs = Entry(root, width=30)
entry_cs.pack()
button = Button(root, width=30, text="Submit", bg="#1EE8AB", command=ShowResult)
button.pack(pady=20)
root.mainloop()